# Generated by Django 5.1.7 on 2025-03-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('posts_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_created_by', to='posts_groups.postsgroup'),
        ),
    ]
