# Generated by Django 5.1.7 on 2025-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permission_created_by_alter_permission_id'),
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users_permissions', to='permissions.permission'),
        ),
    ]
