# Generated by Django 5.1.7 on 2025-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_groups', '0002_alter_postsgroup_id'),
        ('users', '0003_customuser_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='posts_groups.postsgroup'),
        ),
    ]
