# Generated by Django 5.1.7 on 2025-03-20 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
